const ACTION = {
    ADD_ROUTE_SEGMENTS_BY_ROUTE_SHORT_NAME: 'ADD_ROUTE_SEGMENTS_BY_ROUTE_SHORT_NAME',
    REMOVE_ROUTE_SEGMENTS_BY_ROUTE_SHORT_NAME: 'REMOVE_ROUTE_SEGMENTS_BY_ROUTE_SHORT_NAME',
    FETCH_ROUTES_BY_ROUTE_SHORT_NAME_SUCCESS: 'FETCH_ROUTES_BY_ROUTE_SHORT_NAME_SUCCESS',
    FETCH_ROUTES_BY_ROUTE_SHORT_NAME_ERROR: 'FETCH_ROUTES_BY_ROUTE_SHORT_NAME_ERROR',
    FETCH_ROUTES_BY_ROUTE_SHORT_NAME_LOADING: 'FETCH_ROUTES_BY_ROUTE_SHORT_NAME_LOADING',
    FETCH_ROUTE_SEGMENTS_BY_ROUTE_SHORT_NAME_SUCCESS: 'FETCH_ROUTE_SEGMENTS_BY_ROUTE_SHORT_NAME_SUCCESS',
    FETCH_ROUTE_SEGMENTS_BY_ROUTE_SHORT_NAME_ERROR: 'FETCH_ROUTE_SEGMENTS_BY_ROUTE_SHORT_NAME_ERROR',
    FETCH_ROUTE_SEGMENTS_BY_ROUTE_SHORT_NAME_LOADING: 'FETCH_ROUTE_SEGMENTS_BY_ROUTE_SHORT_NAME_LOADING',
    FETCH_INITIAL_ROUTE_SEGMENTS_SUCCESS: 'FETCH_INITIAL_ROUTE_SEGMENTS_SUCCESS',
    FETCH_INITIAL_ROUTE_SEGMENTS_ERROR: 'FETCH_INITIAL_ROUTE_SEGMENTS_ERROR',
    FETCH_INITIAL_ROUTE_SEGMENTS_LOADING: 'FETCH_INITIAL_ROUTE_SEGMENTS_LOADING',
    ON_ANIMATION_SPEED_CHANGE: 'ON_ANIMATION_SPEED_CHANGE',
    ON_TIME_CHANGE: 'ON_TIME_CHANGE',
    ON_TRAIL_LENGTH_CHANGE: 'ON_TRAIL_LENGTH_CHANGE',
    ON_REFRESH_RATE_CHANGE: 'ON_REFRESH_RATE_CHANGE',
    ON_CHANGE_ROUTE_TRAIL_COLOR: 'ON_CHANGE_ROUTE_TRAIL_COLOR',
}

export default ACTION;
