const INITIAL_STATE_TRAIL_LENGTH = 40
const INITIAL_STATE_TIME_IN_SECONDS = 14400
const INITIAL_STATE_ANIMATION_SPEED = 2
const INITIAL_STATE_REFRESH_RATE = 60
const INITIAL_STATE_HELPER_ROUTE_SEGMENTS = [
    '76Y', '145', '34BZ', '59RS', '3A', '3B', '500T', '15B', '146', '319', '97', '98S', 'EM2', '146T', 'ÇM44', '336M', '144K', '131', '121B'
];

const INITIAL_STATE_ADD_HELPER_ROUTE_SEGMENT_IN_EVERY_X_MS = 10000

const TOTAL_SECONDS_IN_A_DAY = 86400

export {
    INITIAL_STATE_TRAIL_LENGTH,
    INITIAL_STATE_TIME_IN_SECONDS,
    INITIAL_STATE_ANIMATION_SPEED,
    INITIAL_STATE_REFRESH_RATE,
    INITIAL_STATE_HELPER_ROUTE_SEGMENTS,
    INITIAL_STATE_ADD_HELPER_ROUTE_SEGMENT_IN_EVERY_X_MS,
    TOTAL_SECONDS_IN_A_DAY,
};